import uuid
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial=True
    dependencies=[("digitalafarin_cms_sites","0001_initial"),("digitalafarin_cms_content","0001_initial")]
    operations=[
        migrations.CreateModel(name="KeywordCluster",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("name",models.CharField(max_length=200)),("intent",models.CharField(blank=True,max_length=50)),("notes",models.TextField(blank=True)),("pillar_entry",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="pillar_clusters",to="digitalafarin_cms_content.contententry")),("site",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="keyword_clusters",to="digitalafarin_cms_sites.site"))]),
        migrations.CreateModel(name="Redirect",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("source_path",models.CharField(max_length=500)),("destination_path",models.CharField(blank=True,max_length=500)),("redirect_type",models.CharField(choices=[("301","301"),("302","302"),("307","307"),("308","308"),("410","410")],default="301",max_length=3)),("is_active",models.BooleanField(default=True)),("hits",models.PositiveBigIntegerField(default=0)),("site",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="redirects",to="digitalafarin_cms_sites.site"))],options={"constraints":[models.UniqueConstraint(fields=("site","source_path"),name="unique_redirect_source")]}),
        migrations.CreateModel(name="SeoMeta",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("title",models.CharField(blank=True,max_length=255)),("description",models.CharField(blank=True,max_length=320)),("canonical_url",models.URLField(blank=True)),("robots_index",models.BooleanField(default=True)),("robots_follow",models.BooleanField(default=True)),("og_title",models.CharField(blank=True,max_length=255)),("og_description",models.CharField(blank=True,max_length=320)),("og_image",models.URLField(blank=True)),("twitter_card",models.CharField(default="summary_large_image",max_length=30)),("focus_keyword",models.CharField(blank=True,max_length=255)),("secondary_keywords",models.JSONField(blank=True,default=list)),("seo_score",models.PositiveSmallIntegerField(default=0)),("analysis",models.JSONField(blank=True,default=dict)),("entry",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name="seo_meta",to="digitalafarin_cms_content.contententry"))]),
        migrations.CreateModel(name="SchemaMarkup",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("schema_type",models.CharField(max_length=80)),("data",models.JSONField(default=dict)),("is_active",models.BooleanField(default=True)),("entry",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="schema_markups",to="digitalafarin_cms_content.contententry"))]),
        migrations.CreateModel(name="Keyword",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("phrase",models.CharField(max_length=255)),("intent",models.CharField(blank=True,max_length=50)),("volume",models.PositiveIntegerField(blank=True,null=True)),("difficulty",models.DecimalField(blank=True,decimal_places=2,max_digits=5,null=True)),("priority",models.PositiveSmallIntegerField(default=50)),("cluster",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="keywords",to="digitalafarin_cms_seo.keywordcluster")),("site",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="keywords",to="digitalafarin_cms_sites.site"))],options={"constraints":[models.UniqueConstraint(fields=("site","phrase"),name="unique_keyword_site_phrase")]}),
        migrations.CreateModel(name="InternalLinkSuggestion",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("anchor_text",models.CharField(max_length=255)),("score",models.DecimalField(decimal_places=2,default=0,max_digits=5)),("status",models.CharField(default="suggested",max_length=20)),("source_entry",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="link_suggestions_from",to="digitalafarin_cms_content.contententry")),("target_entry",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="link_suggestions_to",to="digitalafarin_cms_content.contententry"))]),
        migrations.CreateModel(name="KeywordMapping",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("is_primary",models.BooleanField(default=False)),("target_position",models.PositiveSmallIntegerField(blank=True,null=True)),("entry",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="keyword_mappings",to="digitalafarin_cms_content.contententry")),("keyword",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="mappings",to="digitalafarin_cms_seo.keyword"))],options={"constraints":[models.UniqueConstraint(fields=("keyword","entry"),name="unique_keyword_entry")]})
    ]
