import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial=True
    dependencies=[("digitalafarin_cms_sites","0001_initial"),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name="Category",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("name",models.CharField(max_length=160)),("slug",models.SlugField(max_length=160)),("parent",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="children",to="digitalafarin_cms_content.category")),("site",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="categories",to="digitalafarin_cms_sites.site"))],options={"constraints":[models.UniqueConstraint(fields=("site","slug"),name="unique_category_site_slug")]}),
        migrations.CreateModel(name="ContentTypeDefinition",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("name",models.CharField(max_length=120)),("slug",models.SlugField(max_length=120)),("schema",models.JSONField(blank=True,default=dict,help_text="Custom field definitions")),("icon",models.CharField(blank=True,max_length=50)),("is_public",models.BooleanField(default=True)),("site",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="content_types",to="digitalafarin_cms_sites.site"))],options={"constraints":[models.UniqueConstraint(fields=("site","slug"),name="unique_content_type_site_slug")]}),
        migrations.CreateModel(name="Menu",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("name",models.CharField(max_length=120)),("key",models.SlugField(max_length=120)),("site",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="menus",to="digitalafarin_cms_sites.site"))],options={"constraints":[models.UniqueConstraint(fields=("site","key"),name="unique_menu_site_key")]}),
        migrations.CreateModel(name="ReusableBlock",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("name",models.CharField(max_length=160)),("key",models.SlugField(max_length=160)),("block",models.JSONField(default=dict)),("site",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="reusable_blocks",to="digitalafarin_cms_sites.site"))],options={"constraints":[models.UniqueConstraint(fields=("site","key"),name="unique_reusable_block_key")]}),
        migrations.CreateModel(name="Tag",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("name",models.CharField(max_length=160)),("slug",models.SlugField(max_length=160)),("site",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="tags",to="digitalafarin_cms_sites.site"))],options={"constraints":[models.UniqueConstraint(fields=("site","slug"),name="unique_tag_site_slug")]}),
        migrations.CreateModel(name="ContentEntry",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("title",models.CharField(max_length=255)),("slug",models.SlugField(max_length=255)),("path",models.CharField(help_text="Canonical site path, e.g. /blog/example/",max_length=500)),("excerpt",models.TextField(blank=True)),("blocks",models.JSONField(blank=True,default=list)),("custom_fields",models.JSONField(blank=True,default=dict)),("status",models.CharField(choices=[("draft","Draft"),("review","Review"),("scheduled","Scheduled"),("published","Published"),("archived","Archived")],default="draft",max_length=20)),("published_at",models.DateTimeField(blank=True,null=True)),("scheduled_at",models.DateTimeField(blank=True,null=True)),("is_featured",models.BooleanField(default=False)),("author",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="cms_entries",to=settings.AUTH_USER_MODEL)),("categories",models.ManyToManyField(blank=True,related_name="entries",to="digitalafarin_cms_content.category")),("content_type",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="entries",to="digitalafarin_cms_content.contenttypedefinition")),("parent",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="children",to="digitalafarin_cms_content.contententry")),("site",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="entries",to="digitalafarin_cms_sites.site")),("tags",models.ManyToManyField(blank=True,related_name="entries",to="digitalafarin_cms_content.tag"))],options={"ordering":["-published_at","-created_at"],"constraints":[models.UniqueConstraint(fields=("site","path"),name="unique_entry_site_path")]}),
        migrations.CreateModel(name="ContentRevision",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("number",models.PositiveIntegerField()),("snapshot",models.JSONField(default=dict)),("note",models.CharField(blank=True,max_length=255)),("created_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL)),("entry",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="revisions",to="digitalafarin_cms_content.contententry"))],options={"ordering":["-number"],"constraints":[models.UniqueConstraint(fields=("entry","number"),name="unique_revision_number")]}),
        migrations.CreateModel(name="MenuItem",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("label",models.CharField(max_length=160)),("url",models.CharField(max_length=500)),("sort_order",models.PositiveIntegerField(default=0)),("is_external",models.BooleanField(default=False)),("menu",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="items",to="digitalafarin_cms_content.menu")),("parent",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name="children",to="digitalafarin_cms_content.menuitem"))],options={"ordering":["sort_order","created_at"]})
    ]
