# Generated by Django 5.2.17 on 2026-09-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalafarin_cms_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contententry',
            name='path_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automatic')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='contenttypedefinition',
            name='collection_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='contenttypedefinition',
            name='entry_path_pattern',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='contententry',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255),
        ),
    ]
